### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by qiaoqiangPro** [Negin-Ghamsarian/Transformation-Invariant-Self-Training-MICCAI23#1]
Hello, can you provide your dasetset for training?

**Comment by Negin-Ghamsarian** [comment]
The following datasets are publicly available:

MRI: https://liuquande.github.io/SAML/
RETOUCH: https://retouch.grand-challenge.org/
CaDIS: https://www.sciencedirect.com/science/article/pii/S1361841521000992

The Cat101 segmentation dataset is a subset of Cataract-1K annotations (https://arxiv.org/abs/2312.06295) and will soon be made available.

**Comment by Negin-Ghamsarian** [comment]
> Hello, can you provide your dasetset for training?

Hello! The following datasets are publicly available:

MRI: https://liuquande.github.io/SAML/
RETOUCH: https://retouch.grand-challenge.org/
CaDIS: https://www.sciencedirect.com/science/article/pii/S1361841521000992

The Cat101 segmentation dataset is a subset of Cataract-1K annotations (https://arxiv.org/abs/2312.06295) and will soon be made available.

**Comment by qiaoqiangPro** [comment]
Thank you very much for your prompt answer, I will go to complete the download of the data, if I encounter problems again want to ask you for advice, I hope you can give answers!
Best wishes!

**Comment by qiaoqiangPro** [comment]
Hi, I downloaded RETOUCH-TrainingSet-Spectralis and RETOUCH-TrainingSet-Topcon, and I see that you need to convert to img images right, I'm currently raw and mhd, do you have some details on how to handle this? I'm having some difficulty reproducing it, maybe too many folders
![1702547809419](https://github.com/Negin-Ghamsarian/Transformation-Invariant-Self-Training-MICCAI2023/assets/80230735/2ffe4c0f-97bc-40bb-bf19-62a4545b9f7b)

**Comment by qiaoqiangPro** [comment]
Hi, I found that the RETOUCH dataset uses csv to indicate the data location, and you didn't find train_IDs_CSV and test_IDs_CSV in your csv samples, so maybe this way I don't know the division of your data right?

![image](https://github.com/Negin-Ghamsarian/Transformation-Invariant-Self-Training-MICCAI2023/assets/80230735/9284a084-d181-4f85-b52a-c6655d248868)
![image](https://github.com/Negin-Ghamsarian/Transformation-Invariant-Self-Training-MICCAI2023/assets/80230735/25fd2e40-4b04-4313-8e9b-4ecb06a8cc12)

**Comment by Negin-Ghamsarian** [comment]
> Hi, I downloaded RETOUCH-TrainingSet-Spectralis and RETOUCH-TrainingSet-Topcon, and I see that you need to convert to img images right, I'm currently raw and mhd, do you have some details on how to handle this? I'm having some difficulty reproducing it, maybe too many folders ![1702547809419](https://private-user-images.githubusercontent.com/80230735/290479485-2ffe4c0f-97bc-40bb-bf19-62a4545b9f7b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTA0Nzk0ODUtMmZmZTRjMGYtOTdiYy00MGJiLWJmMTktNjJhNDU0NWI5ZjdiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwY2JkNjRjZDFhYmIxMDYzMjM1ZDU3YTdiNWI5MDllY2U2NjA0NTI5YmI2MmMxM2YzZTRhZWRlOGE5ZDUzOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-xcNZ760_TrenVgKVyDpmT6cg7L2bcaUkhbkuv0Eqs)

Hello! The dataset creation codes for the RETOUCH dataset are added. You should use the code itk_reader.py and adapt the directories' paths for each device (Spectralis and Topcon). Afterward, using Fluid_Separation.py, you can exclude the IRF fluids.

**Comment by Negin-Ghamsarian** [comment]
> Hi, I found that the RETOUCH dataset uses csv to indicate the data location, and you didn't find train_IDs_CSV and test_IDs_CSV in your csv samples, so maybe this way I don't know the division of your data right?
> 
> ![image](https://private-user-images.githubusercontent.com/80230735/291052807-9284a084-d181-4f85-b52a-c6655d248868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4MDctOTI4NGEwODQtZDE4MS00Zjg1LWI1MmEtYzY2NTVkMjQ4ODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYjRmMjUxMDYzNThjMmU1MjllOTFkZGVlYTQ2M2Y5ZWZhNzVkM2ZhNTliZWQ2YmM4N2NhZGFhNjVkYWMzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P_YqLrnoUdOgI2MHOJYW6DibbPtwhfAweuq1xZgebxI) ![image](https://private-user-images.githubusercontent.com/80230735/291052895-25fd2e40-4b04-4313-8e9b-4ecb06a8cc12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4OTUtMjVmZDJlNDAtNGIwNC00MzEzLThlOWItNGVjYjA2YThjYzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMTU2YzA5OWY5Yzk0ZDRlMDk4NWJmYWIyY2RjMTkyYmQ0NThiMzlkMDJkMjg5YTdmYTAzYTk4YzRkMWY0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mcMZOKrgP8WpzfkfcUjEGkPkHjoAmhkHKWk7-IkjZfg)

Hello! The TrainIDs used for training on the IRF fluids are under TrainIDs_RETOUCH_DA, which are uploaded.

Best regards,

**Comment by qiaoqiangPro** [comment]
> > Hi, I found that the RETOUCH dataset uses csv to indicate the data location, and you didn't find train_IDs_CSV and test_IDs_CSV in your csv samples, so maybe this way I don't know the division of your data right?
> > ![image](https://private-user-images.githubusercontent.com/80230735/291052807-9284a084-d181-4f85-b52a-c6655d248868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4MDctOTI4NGEwODQtZDE4MS00Zjg1LWI1MmEtYzY2NTVkMjQ4ODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYjRmMjUxMDYzNThjMmU1MjllOTFkZGVlYTQ2M2Y5ZWZhNzVkM2ZhNTliZWQ2YmM4N2NhZGFhNjVkYWMzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P_YqLrnoUdOgI2MHOJYW6DibbPtwhfAweuq1xZgebxI) ![image](https://private-user-images.githubusercontent.com/80230735/291052895-25fd2e40-4b04-4313-8e9b-4ecb06a8cc12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4OTUtMjVmZDJlNDAtNGIwNC00MzEzLThlOWItNGVjYjA2YThjYzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMTU2YzA5OWY5Yzk0ZDRlMDk4NWJmYWIyY2RjMTkyYmQ0NThiMzlkMDJkMjg5YTdmYTAzYTk4YzRkMWY0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mcMZOKrgP8WpzfkfcUjEGkPkHjoAmhkHKWk7-IkjZfg)
> 
> Hello! The TrainIDs used for training on the IRF fluids are under TrainIDs_RETOUCH_DA, which are uploaded.
> 
> Best regards,

**Comment by qiaoqiangPro** [comment]
> > Hi, I found that the RETOUCH dataset uses csv to indicate the data location, and you didn't find train_IDs_CSV and test_IDs_CSV in your csv samples, so maybe this way I don't know the division of your data right?
> > ![image](https://private-user-images.githubusercontent.com/80230735/291052807-9284a084-d181-4f85-b52a-c6655d248868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4MDctOTI4NGEwODQtZDE4MS00Zjg1LWI1MmEtYzY2NTVkMjQ4ODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYjRmMjUxMDYzNThjMmU1MjllOTFkZGVlYTQ2M2Y5ZWZhNzVkM2ZhNTliZWQ2YmM4N2NhZGFhNjVkYWMzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P_YqLrnoUdOgI2MHOJYW6DibbPtwhfAweuq1xZgebxI) ![image](https://private-user-images.githubusercontent.com/80230735/291052895-25fd2e40-4b04-4313-8e9b-4ecb06a8cc12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4OTUtMjVmZDJlNDAtNGIwNC00MzEzLThlOWItNGVjYjA2YThjYzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMTU2YzA5OWY5Yzk0ZDRlMDk4NWJmYWIyY2RjMTkyYmQ0NThiMzlkMDJkMjg5YTdmYTAzYTk4YzRkMWY0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mcMZOKrgP8WpzfkfcUjEGkPkHjoAmhkHKWk7-IkjZfg)
> 
> Hello! The TrainIDs used for training on the IRF fluids are under TrainIDs_RETOUCH_DA, which are uploaded.
> 
> Best regards,

Hi, Thanks a lot for your reply and addition, I have successfully run the code you added and got the TrainIDs_RETOUCH_DA folder.
Your paper mentions OCT data labeled training images (from source domain), unlabeled training images (from target domain) and average number of test images per fold (391,569,115).
In TrainIDs_RETOUCH_DA the files with suffix _0.csv _1.csv _2.csv _3.csv in each fold should be the labeled training images (from the source domain), the number of files I uploaded with your new uploads is the same, it's around (102+96+113+110)/4=105 png images, which is very far away from the 391 you mentioned. very far.
Unlabeled training images (from the target domain): (572+454+338+221)/4=396, again a big difference from the 569 mentioned in the paper, maybe I'm misunderstanding it, I'm requesting your answer.
Best wishes

**Comment by Negin-Ghamsarian** [comment]
> > > Hi, I found that the RETOUCH dataset uses csv to indicate the data location, and you didn't find train_IDs_CSV and test_IDs_CSV in your csv samples, so maybe this way I don't know the division of your data right?
> > > ![image](https://private-user-images.githubusercontent.com/80230735/291052807-9284a084-d181-4f85-b52a-c6655d248868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4MDctOTI4NGEwODQtZDE4MS00Zjg1LWI1MmEtYzY2NTVkMjQ4ODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYjRmMjUxMDYzNThjMmU1MjllOTFkZGVlYTQ2M2Y5ZWZhNzVkM2ZhNTliZWQ2YmM4N2NhZGFhNjVkYWMzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P_YqLrnoUdOgI2MHOJYW6DibbPtwhfAweuq1xZgebxI) ![image](https://private-user-images.githubusercontent.com/80230735/291052895-25fd2e40-4b04-4313-8e9b-4ecb06a8cc12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4OTUtMjVmZDJlNDAtNGIwNC00MzEzLThlOWItNGVjYjA2YThjYzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMTU2YzA5OWY5Yzk0ZDRlMDk4NWJmYWIyY2RjMTkyYmQ0NThiMzlkMDJkMjg5YTdmYTAzYTk4YzRkMWY0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mcMZOKrgP8WpzfkfcUjEGkPkHjoAmhkHKWk7-IkjZfg)
> > 
> > 
> > Hello! The TrainIDs used for training on the IRF fluids are under TrainIDs_RETOUCH_DA, which are uploaded.
> > Best regards,
> 
> Hi, Thanks a lot for your reply and addition, I have successfully run the code you added and got the TrainIDs_RETOUCH_DA folder. Your paper mentions OCT data labeled training images (from source domain), unlabeled training images (from target domain) and average number of test images per fold (391,569,115). In TrainIDs_RETOUCH_DA the files with suffix _0.csv _1.csv _2.csv _3.csv in each fold should be the labeled training images (from the source domain), the number of files I uploaded with your new uploads is the same, it's around (102+96+113+110)/4=105 png images, which is very far away from the 391 you mentioned. very far. Unlabeled training images (from the target domain): (572+454+338+221)/4=396, again a big difference from the 569 mentioned in the paper, maybe I'm misunderstanding it, I'm requesting your answer. Best wishes

It seems you mistakenly considered "SpectralisVsTopcon_" CSV files as supervised/semi/test sets, while "SpectralisVsTopcon4_" CSV files correspond to the dataset used in this paper (as referenced in the config files under configs_RETOUCH_DA_scSENet_ST4). I will later remove these unnecessary files to avoid further misunderstanding.

**Comment by qiaoqiangPro** [comment]
> > > > Hi, I found that the RETOUCH dataset uses csv to indicate the data location, and you didn't find train_IDs_CSV and test_IDs_CSV in your csv samples, so maybe this way I don't know the division of your data right?
> > > > ![image](https://private-user-images.githubusercontent.com/80230735/291052807-9284a084-d181-4f85-b52a-c6655d248868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4MDctOTI4NGEwODQtZDE4MS00Zjg1LWI1MmEtYzY2NTVkMjQ4ODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYjRmMjUxMDYzNThjMmU1MjllOTFkZGVlYTQ2M2Y5ZWZhNzVkM2ZhNTliZWQ2YmM4N2NhZGFhNjVkYWMzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P_YqLrnoUdOgI2MHOJYW6DibbPtwhfAweuq1xZgebxI) ![image](https://private-user-images.githubusercontent.com/80230735/291052895-25fd2e40-4b04-4313-8e9b-4ecb06a8cc12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4OTUtMjVmZDJlNDAtNGIwNC00MzEzLThlOWItNGVjYjA2YThjYzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMTU2YzA5OWY5Yzk0ZDRlMDk4NWJmYWIyY2RjMTkyYmQ0NThiMzlkMDJkMjg5YTdmYTAzYTk4YzRkMWY0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mcMZOKrgP8WpzfkfcUjEGkPkHjoAmhkHKWk7-IkjZfg)
> > > 
> > > 
> > > Hello! The TrainIDs used for training on the IRF fluids are under TrainIDs_RETOUCH_DA, which are uploaded.
> > > Best regards,
> > 
> > 
> > Hi, Thanks a lot for your reply and addition, I have successfully run the code you added and got the TrainIDs_RETOUCH_DA folder. Your paper mentions OCT data labeled training images (from source domain), unlabeled training images (from target domain) and average number of test images per fold (391,569,115). In TrainIDs_RETOUCH_DA the files with suffix _0.csv _1.csv _2.csv _3.csv in each fold should be the labeled training images (from the source domain), the number of files I uploaded with your new uploads is the same, it's around (102+96+113+110)/4=105 png images, which is very far away from the 391 you mentioned. very far. Unlabeled training images (from the target domain): (572+454+338+221)/4=396, again a big difference from the 569 mentioned in the paper, maybe I'm misunderstanding it, I'm requesting your answer. Best wishes
> 
> It seems you mistakenly considered "SpectralisVsTopcon_" CSV files as supervised/semi/test sets, while "SpectralisVsTopcon4_" CSV files correspond to the dataset used in this paper (as referenced in the config files under configs_RETOUCH_DA_scSENet_ST4). I will later remove these unnecessary files to avoid further misunderstanding.

Yes, sorry about that, there are too many files and I may have caused confusion, I followed your newly uploaded dataset_creation_RETOUCH folder settings and got the （all 16 files）
![image](https://github.com/Negin-Ghamsarian/Transformation-Invariant-Self-Training-MICCAI2023/assets/80230735/9fc7edc6-6304-428b-8682-ae734d7d3235)

Your TrainIDs_RETOUCH_DA folder has, SpectralisVsCirrus, but you didn't consider the Cirrus data in your paper right, I can ignore it as well!

**Comment by qiaoqiangPro** [comment]
> > > > Hi, I found that the RETOUCH dataset uses csv to indicate the data location, and you didn't find train_IDs_CSV and test_IDs_CSV in your csv samples, so maybe this way I don't know the division of your data right?
> > > > ![image](https://private-user-images.githubusercontent.com/80230735/291052807-9284a084-d181-4f85-b52a-c6655d248868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4MDctOTI4NGEwODQtZDE4MS00Zjg1LWI1MmEtYzY2NTVkMjQ4ODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYjRmMjUxMDYzNThjMmU1MjllOTFkZGVlYTQ2M2Y5ZWZhNzVkM2ZhNTliZWQ2YmM4N2NhZGFhNjVkYWMzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P_YqLrnoUdOgI2MHOJYW6DibbPtwhfAweuq1xZgebxI) ![image](https://private-user-images.githubusercontent.com/80230735/291052895-25fd2e40-4b04-4313-8e9b-4ecb06a8cc12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODUwMzEsIm5iZiI6MTcwMzI4NDczMSwicGF0aCI6Ii84MDIzMDczNS8yOTEwNTI4OTUtMjVmZDJlNDAtNGIwNC00MzEzLThlOWItNGVjYjA2YThjYzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIyMzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMTU2YzA5OWY5Yzk0ZDRlMDk4NWJmYWIyY2RjMTkyYmQ0NThiMzlkMDJkMjg5YTdmYTAzYTk4YzRkMWY0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mcMZOKrgP8WpzfkfcUjEGkPkHjoAmhkHKWk7-IkjZfg)
> > > 
> > > 
> > > Hello! The TrainIDs used for training on the IRF fluids are under TrainIDs_RETOUCH_DA, which are uploaded.
> > > Best regards,
> > 
> > 
> > Hi, Thanks a lot for your reply and addition, I have successfully run the code you added and got the TrainIDs_RETOUCH_DA folder. Your paper mentions OCT data labeled training images (from source domain), unlabeled training images (from target domain) and average number of test images per fold (391,569,115). In TrainIDs_RETOUCH_DA the files with suffix _0.csv _1.csv _2.csv _3.csv in each fold should be the labeled training images (from the source domain), the number of files I uploaded with your new uploads is the same, it's around (102+96+113+110)/4=105 png images, which is very far away from the 391 you mentioned. very far. Unlabeled training images (from the target domain): (572+454+338+221)/4=396, again a big difference from the 569 mentioned in the paper, maybe I'm misunderstanding it, I'm requesting your answer. Best wishes
> 
> It seems you mistakenly considered "SpectralisVsTopcon_" CSV files as supervised/semi/test sets, while "SpectralisVsTopcon4_" CSV files correspond to the dataset used in this paper (as referenced in the config files under configs_RETOUCH_DA_scSENet_ST4). I will later remove these unnecessary files to avoid further misunderstanding.

Hi, Negin. I apologize, I'm still confused at the moment, the first thing I'd like to confirm is whether the test set division of the 0th fold of Spectrails in RETOUCH is including these four goes?

![image](https://github.com/Negin-Ghamsarian/Transformation-Invariant-Self-Training-MICCAI2023/assets/80230735/1cfaf260-3328-454c-a61b-16116eed8893)
I found that the code I followed to divide the dataset as you provided, in the processed result, firstly, the file name is SpectralisVsTopcon_0
which is not SpectralisVsTopcon4_0 as you corrected, and I can't be sure if they represent the same thing, and secondly, I found that file 026 exists in the SpectralisVsTopcon4_0.csv file (which is supposed to include only the training images of the source domains) that you provided, and I'm thinking that it shouldn't exist in the training set, and that it's already been partitioned to the SourceTest.

![image](https://github.com/Negin-Ghamsarian/Transformation-Invariant-Self-Training-MICCAI2023/assets/80230735/5c18ac41-0109-4cab-a64a-ee946908f3ab)
Best wishes.

**Comment by Negin-Ghamsarian** [comment]
> followed to divide the dataset as you provide

The config files are already provided under configs_RETOUCH_DA_scSENet_ST4. The (dataset_creation_RETOUCH/subdataset_generator_RETOUCH_DA.py) code is a sample for dataset creation scheme in case you would like to create CSV files with other portions or strategies.

**Comment by qiaoqiangPro** [comment]
> The config files are already provided under configs_RETOUCH_DA_scSENet_ST4. The (dataset_creation_RETOUCH/subdataset_generator_RETOUCH_DA.py) code is a sample for dataset creation scheme in case you would like to create CSV files with other portions or strategies.

Ok, Negin. i understand, thanks for the reply!
Best wishes.
